### ISSUE TITLE
Review: please add unit tests for the server logic

### ISSUE THREAD

**Issue by mrtnzlml** [radkag/kiwi#1]
Hi Radka 👋. I internally reviewed your task and I am still missing one important thing. Could you please provide unit tests for your server-side logic? Please, let me know when you'll add them so I can check it again.

Thanks - Martin from Kiwi.com

**Comment by radkag** [comment]
Hello Martin, I added tests for /convertor route. Now you can check it out. :))

**Comment by mrtnzlml** [comment]
Thx. Someone will contact you soon... :)
